spring:
  application:
    name: project-back
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kb_project
    username: root
    password: ''             # MySQL 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create        # 최초 실행 시 create, 이후 update로 변경
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  servlet:
    session:
      persistent: false

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:}
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON:}
